CREATE TYPE "SubscriptionState" AS ENUM ('DETECTED', 'SLAYING', 'SLAIN', 'SHIELDED');
CREATE TYPE "SubscriptionSource" AS ENUM ('ACTIVE_REQUEST', 'FREE_TRIAL', 'AUTOMATED_DETECTION');
CREATE TYPE "BountyType" AS ENUM ('BOUNTY', 'SHIELD');

ALTER TABLE "User"
ADD COLUMN "stripeCustomerId" TEXT UNIQUE;

ALTER TABLE "Subscription"
ADD COLUMN "state" "SubscriptionState" NOT NULL DEFAULT 'DETECTED',
ADD COLUMN "source" "SubscriptionSource" NOT NULL DEFAULT 'AUTOMATED_DETECTION',
ADD COLUMN "trialExpiresAt" TIMESTAMP(3);

ALTER TABLE "Bounty"
ADD COLUMN "type" "BountyType" NOT NULL DEFAULT 'BOUNTY';
